#!/usr/bin/env python3
"""Create and run an iOS Settings smoke task.

Usage:
  API_BASE=http://localhost:8003/api/v1 DEVICE_ID=<ios-udid> python3 device-farm/scripts/ios_smoke_task_flow.py

Optional:
  API_KEY=<api-key>
  TIMEOUT_SECONDS=180
  POLL_INTERVAL=3
  SCRIPT_FILE=device-farm/scripts/examples/ios_settings_smoke.py
"""

from __future__ import annotations

import json
import os
import sys
import time
from pathlib import Path
from typing import Optional
import urllib.error
import urllib.request


ROOT_DIR = Path(__file__).resolve().parents[1]
API_BASE = os.getenv("API_BASE", "http://localhost:8003/api/v1").rstrip("/")
DEVICE_ID = os.getenv("DEVICE_ID", "")
API_KEY = os.getenv("API_KEY", "")
TIMEOUT_SECONDS = int(os.getenv("TIMEOUT_SECONDS", "180"))
POLL_INTERVAL = float(os.getenv("POLL_INTERVAL", "3"))
SCRIPT_FILE = Path(os.getenv("SCRIPT_FILE", str(ROOT_DIR / "scripts/examples/ios_settings_smoke.py")))


def request(method: str, path: str, payload: Optional[dict] = None):
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if API_KEY:
        headers["X-API-Key"] = API_KEY

    req = urllib.request.Request(
        f"{API_BASE}{path}",
        data=data,
        headers=headers,
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as response:
            body = response.read().decode("utf-8")
            return None if not body else json.loads(body)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8")
        raise RuntimeError(f"{method} {path} failed: HTTP {exc.code} {detail}") from exc


def load_script_content() -> str:
    if not SCRIPT_FILE.exists():
        raise RuntimeError(f"SCRIPT_FILE does not exist: {SCRIPT_FILE}")
    return SCRIPT_FILE.read_text(encoding="utf-8")


def print_logs(task_id: str) -> None:
    logs = request("GET", f"/tasks/{task_id}/logs?limit=200") or []
    print(f"log count: {len(logs)}")
    for item in logs:
        timestamp = item.get("timestamp", "")
        level = item.get("level", "INFO")
        line_number = item.get("line_number")
        line = f"line {line_number} " if line_number else ""
        print(f"[{timestamp}] {level} {line}{item.get('message', '')}")


def main() -> int:
    if not DEVICE_ID:
        print("DEVICE_ID is required", file=sys.stderr)
        return 2

    content = load_script_content()
    script = request(
        "POST",
        "/scripts",
        {
            "name": f"ios-settings-smoke-{int(time.time())}",
            "description": "iOS Settings smoke generated by device-farm/scripts/ios_smoke_task_flow.py",
            "script_type": "python",
            "content": content,
            "tags": ["ios", "smoke", "settings"],
        },
    )
    print(f"created script: {script['id']}")

    task = request(
        "POST",
        "/tasks",
        {
            "script_id": script["id"],
            "device_id": DEVICE_ID,
            "device_platform": "ios",
            "device_capabilities": {"noReset": True},
            "parameters": {},
        },
    )
    task_id = task["id"]
    print(f"created task: {task_id}")

    deadline = time.time() + TIMEOUT_SECONDS
    final_statuses = {"success", "failed", "cancelled"}
    while time.time() < deadline:
        task = request("GET", f"/tasks/{task_id}")
        status = task["status"]
        print(f"task status: {status}")
        if status in final_statuses:
            print_logs(task_id)
            if status == "success":
                print("iOS smoke passed")
                return 0
            print(f"iOS smoke finished with status={status}, error={task.get('error') or ''}", file=sys.stderr)
            return 1
        time.sleep(POLL_INTERVAL)

    print(f"task timed out after {TIMEOUT_SECONDS}s, cancelling: {task_id}", file=sys.stderr)
    try:
        request("DELETE", f"/tasks/{task_id}")
    finally:
        print_logs(task_id)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
