#!/usr/bin/env python3
"""Smoke test for script/task execution flow.

Usage:
  API_BASE=http://localhost:8003/api/v1 DEVICE_ID=<device-id> python3 device-farm/scripts/smoke_task_flow.py

The script creates a Python script, creates a task on the target device,
polls the task, fetches logs, and cancels it if it is still active.
"""

from __future__ import annotations

import json
import os
import sys
import time
from typing import Optional
import urllib.error
import urllib.request


API_BASE = os.getenv("API_BASE", "http://localhost:8003/api/v1").rstrip("/")
DEVICE_ID = os.getenv("DEVICE_ID", "")
API_KEY = os.getenv("API_KEY", "")


def request(method: str, path: str, payload: Optional[dict] = None):
    data = None if payload is None else json.dumps(payload).encode("utf-8")
    headers = {"Content-Type": "application/json"}
    if API_KEY:
        headers["X-API-Key"] = API_KEY

    req = urllib.request.Request(
        f"{API_BASE}{path}",
        data=data,
        headers=headers,
        method=method,
    )
    try:
        with urllib.request.urlopen(req, timeout=20) as response:
            body = response.read().decode("utf-8")
            return None if not body else json.loads(body)
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8")
        raise RuntimeError(f"{method} {path} failed: HTTP {exc.code} {detail}") from exc


def main() -> int:
    if not DEVICE_ID:
        print("DEVICE_ID is required", file=sys.stderr)
        return 2

    script = request(
        "POST",
        "/scripts",
        {
            "name": f"smoke-flow-{int(time.time())}",
            "description": "Smoke flow generated by device-farm/scripts/smoke_task_flow.py",
            "script_type": "python",
            "content": "\n".join(
                [
                    'app.log("smoke flow script start")',
                    "app.wait(30)",
                    'app.log("smoke flow script end")',
                    "test_pass()",
                ]
            ),
            "tags": ["smoke", "flow"],
        },
    )
    print(f"created script: {script['id']}")

    task = request(
        "POST",
        "/tasks",
        {
            "script_id": script["id"],
            "device_id": DEVICE_ID,
            "device_platform": "android",
            "device_capabilities": {"automationName": "UiAutomator2", "noReset": True},
            "parameters": {},
        },
    )
    print(f"created task: {task['id']}")

    final_statuses = {"success", "failed", "cancelled"}
    for _ in range(10):
        task = request("GET", f"/tasks/{task['id']}")
        print(f"task status: {task['status']}")
        if task["status"] in final_statuses:
            break
        if task["status"] in {"pending", "running"}:
            request("DELETE", f"/tasks/{task['id']}")
            task = request("GET", f"/tasks/{task['id']}")
            print(f"cancelled task status: {task['status']}")
            break
        time.sleep(2)

    logs = request("GET", f"/tasks/{task['id']}/logs")
    print(f"log count: {len(logs or [])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
